# Generated by Django 3.0.7 on 2020-06-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-available',)},
        ),
    ]
